-- task_4.sql
-- Full description of the 'books' table without DESCRIBE, EXPLAIN, or ANALYZE

-- Show the complete CREATE TABLE statement
SHOW CREATE TABLE books;

-- Also show detailed column info from INFORMATION_SCHEMA
SELECT
  COLUMN_NAME,
  COLUMN_TYPE,
  IS_NULLABLE,
  COLUMN_DEFAULT,
  COLUMN_KEY,
  EXTRA
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_SCHEMA = DATABASE()
  AND TABLE_NAME = 'books'
ORDER BY ORDINAL_POSITION;
